Repository QuiltServerTools/Ledger, pull requests merged in 2021-06, with the labels that each got.

#15 Add support for non-player actions with player sources
  src/main/kotlin/us/potatoboy/ledger/actions/AbstractActionType.kt
  src/main/kotlin/us/potatoboy/ledger/commands/arguments/SearchParamArgument.kt
  src/main/kotlin/us/potatoboy/ledger/listeners/BlockEventListener.kt
Labels: enhancement

#14 Shadow SQLite and exposed to allow for additional mod compat where the devs do not shadow these libraries
  build.gradle
Labels: fix

#16 Add mkdocs
  docs/actions.md
  docs/assets/Ledger-smol.svg
  docs/assets/search-example.png
  docs/assets/status-example.png
  docs/commands/inspect.md
  docs/commands/page.md
  docs/commands/preview.md
  docs/commands/restore.md
  docs/commands/rollback.md
  docs/commands/root.md
  docs/commands/search.md
  docs/commands/status.md
  docs/commands/teleport.md
  docs/config.md
  docs/index.md
  docs/install.md
  docs/networking.md
  docs/parameters.md
  docs/queue.md
  docs/themes.md
  media/Ledger-smol.png
  media/Ledger.afdesign
  media/Ledger.png
  media/Ledger.svg
  mkdocs.yml
Labels: documentation

#11 Add networking testmod
  build.gradle
  src/testmod/java/us/potatoboy/ledger/testmod/mixin/ClientPlayerInteractionManagerMixin.java
  src/testmod/kotlin/us/potatoboy/ledger/testmod/LedgerTest.kt
  src/testmod/kotlin/us/potatoboy/ledger/testmod/commands/InspectCommand.kt
  src/testmod/kotlin/us/potatoboy/ledger/testmod/commands/LedgerTestmodCommand.kt
  src/testmod/kotlin/us/potatoboy/ledger/testmod/commands/SearchCommand.kt
  src/testmod/resources/fabric.mod.json
  src/testmod/resources/ledger-testmod.mixins.json
Labels: enhancement

#30 Track items removed on container break
  gradle.properties
  src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/ItemScattererMixin.java
  src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/SlotMixin.java
  src/main/kotlin/com/github/quiltservertools/ledger/Ledger.kt
  src/main/kotlin/com/github/quiltservertools/ledger/callbacks/ItemInsertCallback.kt
  src/main/kotlin/com/github/quiltservertools/ledger/callbacks/ItemRemoveCallback.kt
  src/main/kotlin/com/github/quiltservertools/ledger/callbacks/PlayerInsertItemCallback.kt
  src/main/kotlin/com/github/quiltservertools/ledger/callbacks/PlayerRemoveItemCallback.kt
  src/main/kotlin/com/github/quiltservertools/ledger/listeners/PlayerEventListener.kt
  src/main/kotlin/com/github/quiltservertools/ledger/listeners/WorldEventListener.kt
  src/main/resources/ledger.mixins.json
Labels: bug

#31 Added permission node to /lg alias
  .editorconfig
  .gitignore
  src/main/kotlin/com/github/quiltservertools/ledger/commands/LedgerCommand.kt
Labels: enhancement

#38 Implement custom attack block callback
  src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/ServerPlayInteractionManagerMixin.java
  src/main/kotlin/com/github/quiltservertools/ledger/callbacks/PlayerBlockAttackCallback.kt
  src/main/kotlin/com/github/quiltservertools/ledger/listeners/PlayerEventListener.kt
  src/main/resources/ledger.mixins.json
Labels: bug

#35 Fix nbt rollback reading
  src/main/kotlin/com/github/quiltservertools/ledger/actions/BlockBreakActionType.kt
  src/main/kotlin/com/github/quiltservertools/ledger/actions/BlockChangeActionType.kt
Labels: bug

#39 Added issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/workflows/build.yml
  build.gradle
Labels: enhancement

#42 Update translations
  gradle.properties
Labels: fix

#43 Fix AND statement grouping in database selections
  src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
Labels: bug

#44 Fix hardcoded version in fabric.mod.json
  build.gradle
  src/main/kotlin/com/github/quiltservertools/ledger/commands/subcommands/StatusCommand.kt
  src/main/resources/fabric.mod.json
Labels: bug

#48 Added a check if update packet is null - Fixes #47
  src/main/java/com/github/quiltservertools/ledger/mixin/callbacks/ServerPlayInteractionManagerMixin.java
Labels: bug

#52 Fix select issue with block-break
  src/main/kotlin/com/github/quiltservertools/ledger/database/DatabaseManager.kt
Labels: bug
